- name: configure pacman
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#?VerbosePkgLists'
    line: 'VerbosePkgLists'

- name: install pkgs
  community.general.pacman:
    name:
      - bash-completion
      - btop
      - curl
      - discord
      - less
      - lib32-mesa
      - lib32-vulkan-radeon
      - man-db
      - mesa
      - npm
      - steam
      - stow
      - sway
      - tmux
      - tree
      - vim
      - vulkan-radeon
      - waybar
      - wiremix
      - xf86-video-amdgpu
    state: present

- name: create default .config
  ansible.builtin.file:
    path: ~/.config
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    state: directory
    mode: '0755'

- name: clone dotfiles repo
  ansible.builtin.git:
    repo: 'git@github.com:spencerdennison/dotfiles.git'
    dest: ~/dotfiles
    key_file: ~/.ssh/github
    accept_hostkey: true

- name: symlink .config
  ansible.builtin.command: stow .
  args:
    chdir: ~/dotfiles
