- name: pacman pkgs
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_facts['distribution'] == "archlinux"

- name: apt pkgs
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  when: 
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution'] == "Ubuntu"
