- name: install boinc pkgs
  community.general.pacman:
    name:
      - boinc
      - boinctui
    state: present

- name: start boinc service
  ansible.builtin.service:
    name: boinc-client
    enabled: true
    state: started

- name: configure boinc
  ansible.builtin.service:
    path: /var/lib/boinc/gui_rpc_auth.cfg 
    line: 
